import type { Member, PaymentAlert } from "./types"

export const mockMembers: Member[] = [
  {
    id: "1",
    email: "mosque@epma.org",
    name: "Easton Phillipsburg Muslim Association",
    phone: "+1 555-123-4567",
    subscriptions: [
      {
        id: "sub-1",
        type: "mosque",
        name: "EPMA Mosque",
        status: "active",
        price: 100,
        startDate: "2024-01-01",
        paymentStartDate: "2024-01-01",
        nextBillingDate: "2025-01-01",
        location: "Easton, PA",
        photo: "/images/mosque-20home.png",
        photos: ["/images/mosque-20home.png", "/mosque-prayer-hall.png", "/mosque-exterior-view.jpg"],
        description: "Faith, learning, and service in Easton-Phillipsburg. Serving the Muslim community since 1995.",
        contactName: "Imam Ahmad Hassan",
        thirdPartyLogins: [
          { platform: "Amanah App", username: "epma_admin", password: "••••••••" },
          { platform: "Stripe", username: "epma_stripe", password: "••••••••" },
        ],
        documents: [
          { id: "doc-1", name: "Tax Exempt Certificate", url: "#", uploadedAt: "2024-01-01", type: "pdf" },
          { id: "doc-2", name: "Registration Documents", url: "#", uploadedAt: "2024-01-01", type: "pdf" },
          { id: "doc-3", name: "Insurance Certificate", url: "#", uploadedAt: "2024-02-15", type: "pdf" },
        ],
      },
    ],
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    email: "halal@restaurant.com",
    name: "Halal Delights Restaurant",
    phone: "+1 555-987-6543",
    subscriptions: [
      {
        id: "sub-2",
        type: "business",
        name: "Halal Delights",
        businessName: "Halal Delights Restaurant",
        status: "active",
        price: 10,
        startDate: "2024-06-01",
        paymentStartDate: "2024-06-01",
        nextBillingDate: "2025-01-01",
        category: "Restaurant",
        location: "123 Main Street, New York, NY 10001",
        description:
          "Authentic halal cuisine from around the world. Family-owned since 2010, serving the finest Mediterranean and Middle Eastern dishes.",
        photo: "/halal-restaurant-interior-with-arabic-decor.jpg",
        photos: [
          "/halal-restaurant-interior-with-arabic-decor.jpg",
          "/delicious-halal-food-platter.jpg",
          "/halal-restaurant-kitchen.jpg",
        ],
        website: "www.halaldelights.com",
        contactName: "Mohammed Ali",
        documents: [
          { id: "doc-3", name: "Halal Certificate", url: "#", uploadedAt: "2024-06-01", type: "pdf" },
          { id: "doc-4", name: "Business License", url: "#", uploadedAt: "2024-06-01", type: "pdf" },
          { id: "doc-5", name: "Health Permit", url: "#", uploadedAt: "2024-06-15", type: "pdf" },
        ],
      },
      {
        id: "sub-3",
        type: "coupon",
        name: "10% Off First Order",
        businessName: "Halal Delights Restaurant",
        status: "active",
        price: 10,
        startDate: "2024-06-01",
        paymentStartDate: "2024-06-01",
        nextBillingDate: "2025-01-01",
        offer: "10% off your first order over $25",
        location: "123 Main Street, New York, NY 10001",
        photo: "/delicious-halal-food-platter.jpg",
        photos: ["/delicious-halal-food-platter.jpg", "/halal-food-special-offer.jpg"],
        expiryDate: "2025-06-01",
        terms: "Valid for dine-in and takeout only. Cannot be combined with other offers.",
      },
      {
        id: "sub-4",
        type: "coupon",
        name: "Free Dessert",
        businessName: "Halal Delights Restaurant",
        status: "active",
        price: 10,
        startDate: "2024-06-01",
        paymentStartDate: "2024-06-15",
        nextBillingDate: "2025-01-01",
        offer: "Free dessert with any order over $50",
        location: "123 Main Street, New York, NY 10001",
        photo: "/baklava-dessert-middle-eastern-sweets.jpg",
        photos: ["/baklava-dessert-middle-eastern-sweets.jpg"],
        expiryDate: "2025-03-01",
        terms: "One per customer. Valid on dine-in orders only.",
      },
    ],
    createdAt: "2024-06-01",
  },
  {
    id: "3",
    email: "admin@isbr.org",
    name: "Islamic Society of Basking Ridge",
    phone: "+1 555-456-7890",
    subscriptions: [
      {
        id: "sub-5",
        type: "mosque",
        name: "ISBR Mosque",
        status: "past_due",
        price: 100,
        startDate: "2024-03-01",
        paymentStartDate: "2024-03-01",
        nextBillingDate: "2024-12-01",
        location: "Basking Ridge, NJ",
        photo: "/islamic-society-mosque.jpg",
        photos: ["/islamic-society-mosque.jpg", "/mosque-community-center.jpg"],
        description:
          "Empowering Muslims in Somerset Hills. A vibrant community center for worship, education, and fellowship.",
        contactName: "Dr. Yusuf Ibrahim",
        documents: [],
        thirdPartyLogins: [],
      },
    ],
    createdAt: "2024-03-01",
  },
  {
    id: "4",
    email: "info@crescentbooks.com",
    name: "Crescent Islamic Books",
    phone: "+1 555-321-9876",
    subscriptions: [
      {
        id: "sub-6",
        type: "business",
        name: "Crescent Books",
        businessName: "Crescent Islamic Books & Gifts",
        status: "active",
        price: 10,
        startDate: "2024-08-01",
        paymentStartDate: "2024-08-01",
        nextBillingDate: "2025-01-01",
        category: "Retail",
        location: "456 Oak Avenue, Chicago, IL 60601",
        description:
          "Your source for Islamic books, Qurans, prayer items, and gifts. Serving the community with quality Islamic products.",
        photo: "/islamic-bookstore-interior-with-quran-books.jpg",
        photos: [
          "/islamic-bookstore-interior-with-quran-books.jpg",
          "/beautiful-quran-with-prayer-beads.jpg",
          "/islamic-gifts-and-prayer-items.jpg",
        ],
        website: "www.crescentbooks.com",
        contactName: "Fatima Rahman",
        documents: [{ id: "doc-6", name: "Business License", url: "#", uploadedAt: "2024-08-01", type: "pdf" }],
      },
      {
        id: "sub-7",
        type: "coupon",
        name: "20% Off Ramadan Sale",
        businessName: "Crescent Islamic Books & Gifts",
        status: "active",
        price: 10,
        startDate: "2024-08-01",
        paymentStartDate: "2024-08-15",
        nextBillingDate: "2025-01-01",
        offer: "20% off all Qurans and prayer mats during Ramadan",
        location: "456 Oak Avenue, Chicago, IL 60601",
        photo: "/beautiful-quran-with-prayer-beads.jpg",
        photos: ["/beautiful-quran-with-prayer-beads.jpg"],
        expiryDate: "2025-04-01",
        terms: "Valid during Ramadan only. In-store purchases only.",
      },
    ],
    createdAt: "2024-08-01",
  },
  {
    id: "5",
    email: "contact@noorclothing.com",
    name: "Noor Modest Fashion",
    phone: "+1 555-654-3210",
    subscriptions: [
      {
        id: "sub-8",
        type: "business",
        name: "Noor Fashion",
        businessName: "Noor Modest Fashion",
        status: "active",
        price: 10,
        startDate: "2024-09-15",
        paymentStartDate: "2024-09-15",
        nextBillingDate: "2025-01-15",
        category: "Clothing",
        location: "789 Fashion Blvd, Los Angeles, CA 90001",
        description:
          "Modern modest fashion for Muslim women. Elegant abayas, hijabs, and everyday wear that combines style with modesty.",
        photo: "/modest-fashion-boutique-hijab-clothing-store.jpg",
        photos: [
          "/modest-fashion-boutique-hijab-clothing-store.jpg",
          "/hijab-fashion-collection.jpg",
          "/modest-abaya-dress.jpg",
          "/islamic-modest-wear.jpg",
        ],
        website: "www.noormodest.com",
        contactName: "Aisha Khan",
        documents: [
          { id: "doc-7", name: "Business License", url: "#", uploadedAt: "2024-09-15", type: "pdf" },
          { id: "doc-8", name: "Vendor Agreement", url: "#", uploadedAt: "2024-09-15", type: "pdf" },
        ],
      },
    ],
    createdAt: "2024-09-15",
  },
]

export const mockPaymentAlerts: PaymentAlert[] = [
  {
    id: "alert-1",
    memberId: "3",
    memberName: "Islamic Society of Basking Ridge",
    memberEmail: "admin@isbr.org",
    subscriptionId: "sub-5",
    subscriptionType: "mosque",
    subscriptionName: "ISBR Mosque",
    alertType: "payment_failed",
    createdAt: "2024-12-01",
    resolved: false,
  },
]
